{% set name = "nengo" %}
{% set version = "4.1.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/nengo-{{ version }}.tar.gz
  sha256: 0ed9df055fba64d5c25092d851cf1b65b07086c87ed589977a513729f548a395

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
  run:
    - numpy >=1.13,<2
    - python >={{ python_min }}
    - scipy >=0.13
    - scikit-learn

test:
  imports:
    - nengo
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://www.nengo.ai/nengo
  summary: Tools for building and simulating large-scale neural models
  license: LicenseRef-NENGO
  license_file: LICENSE.rst

extra:
  recipe-maintainers:
    - Tobias-Fischer
